service: aws-lambda-s3

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  architecture: arm64
  region: "eu-west-1"
  
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:s3::::rpayeras-aws-lambda-s3"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3::::rpayeras-aws-lambda-s3/*"

functions:
  thumbnailsList:
    handler: handler.thumbnailsList
    events:
      - http:
          method: get
          path: thumbnails

  imageUpload:
    handler: handler.imageUpload
    events:
      - s3:
          bucket: rpayeras-aws-lambda-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: images/
          existing: true